# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f8d966069859e99c3a3d9be3375f202bf1f5d8b45997ca88ffb48aa1d502eb330533e4fc102cf9029817a001e831527ad8fc9f6434685b80ad711fa514aee04

test:
  secret_key_base: 83f13fe386cb7c5734c09b379a715f7e5bfc30681d10052343850c2d560b957592e6e40b4631530b5b748bc6f75034fa20f5c7f7554ea6658e021c540f7d16d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
